import type { Billet } from '@/types/schema';

export const MOCK_BILLETS: Billet[] = [
    // =============================================================================
    // IT BILLETS (Persona D — IT1 Wilson)
    // =============================================================================
    {
        id: 'b1-uss-halsey',
        title: 'NETWORK SYSTEM ADMIN',
        uic: '21345',
        location: 'SAN DIEGO, CA',
        payGrade: 'E-6',
        nec: 'H08A',
        dutyType: 'SEA',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Lead SysAdmin for USS HALSEY (DDG-97). Security+ required. CANES migration experience preferred.',
        compass: {
            matchScore: 98,
            contextualNarrative: 'This billet is an exceptional match for your profile. Your recent shore tour combined with your NEC H08A certification positions you perfectly to lead the CANES migration team. Completing this sea duty tour will be a strong discriminator for Chief selection next cycle.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b2-nctams-pac',
        title: 'COMM CENTER SUPERVISOR',
        uic: '66890',
        location: 'WAHIAWA, HI',
        payGrade: 'E-6',
        nec: 'H04A',
        dutyType: 'SHORE',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Watch Supervisor at NCTAMS PAC. Shift work involved.',
        compass: {
            matchScore: 89,
            contextualNarrative: 'A solid leadership opportunity in a high-vis shore command. While slightly outside your core sys-admin track, the Watch Supervisor qualification offered here is highly valued. This tour offers stability for your family while broadening your operational comms experience.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b3-devgru',
        title: 'EX TACTICAL COMMS',
        uic: '00012',
        location: 'VIRGINIA BEACH, VA',
        payGrade: 'E-6',
        nec: 'H09A',
        dutyType: 'SEA',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Expeditionary communications support. Screening required.',
        compass: {
            matchScore: 94,
            contextualNarrative: 'An elite, high-tempo assignment reserved for top performers. Your consistent "Early Promote" evaluations make you a prime candidate. This role requires rigorous screening but offers unparalleled training in tactical comms and direct support to special operations forces.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b4-uss-gerald-r-ford',
        title: 'SECURITY MANAGER',
        uic: '23456',
        location: 'NORFOLK, VA',
        payGrade: 'E-6',
        nec: '741A',
        dutyType: 'SEA',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 200 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Manage security protocols and clearances for crew.',
        compass: {
            matchScore: 85,
            contextualNarrative: 'Leverage your attention to detail in this critical program management role. As the Security Manager for a CVN, you will oversee thousands of clearances, giving you direct access to the Command Triad. Ideally suited for someone looking to demonstrate administrative excellence at scale.',
        },
        advertisementStatus: 'projected',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b5-nioc-hawaii',
        title: 'CYBER ANALYST',
        uic: '34567',
        location: 'PEARL HARBOR, HI',
        payGrade: 'E-6',
        nec: 'H10A',
        dutyType: 'SHORE',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 100 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Analyze network traffic for threats.',
        compass: {
            matchScore: 92,
            contextualNarrative: 'Your background in network defense makes you an immediate asset here. This role focuses on active threat hunting and incident response. It is a technical heavy-hitter tour that will qualify you for high-level civilian sector certifications like CISSP and CEH.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b6-uss-ronald-reagan',
        title: 'NETWORK ADMIN',
        uic: '45678',
        location: 'YOKOSUKA, JAPAN',
        payGrade: 'E-6',
        nec: 'H08A',
        dutyType: 'SEA',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 210 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Maintain shipboard networks during deployment.',
        compass: {
            matchScore: 88,
            contextualNarrative: 'Forward Deployed Naval Forces (FDNF) experience is a career accelerator. This sea tour in Japan offers high operational tempo and the chance to lead a large division. While demanding, the promotion rates for sailors completing this tour are significantly above average.',
        },
        advertisementStatus: 'projected',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b7-ncts-san-diego',
        title: 'SATCOM OPERATOR',
        uic: '56789',
        location: 'SAN DIEGO, CA',
        payGrade: 'E-5',
        nec: 'V01A',
        dutyType: 'SHORE',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Operate satellite communications equipment.',
        compass: {
            matchScore: 75,
            contextualNarrative: 'A functional shore duty that keeps you in San Diego. While the technical scope is slightly below your extensive experience, it offers a predictable schedule allowing for college education or off-duty certification work. Good for work-life balance.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b8-uss-constitution',
        title: 'PUBLIC AFFAIRS',
        uic: '67890',
        location: 'BOSTON, MA',
        payGrade: 'E-6',
        nec: 'A01A',
        dutyType: 'SHORE',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 200 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Historic ship duty, public interface required.',
        compass: {
            matchScore: 60,
            contextualNarrative: 'A rare "Special Duty" assignment aboard "Old Ironsides." This is a pivot away from your technical track but offers a unique, once-in-a-lifetime experience. Excellent for public speaking and heritage engagement, though it may pause your technical NEC progression.',
        },
        advertisementStatus: 'closed',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b9-pers-40',
        title: 'DETAILER ASSISTANT',
        uic: '78901',
        location: 'MILLINGTON, TN',
        payGrade: 'E-6',
        nec: '803R',
        dutyType: 'SHORE',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Assist in detailer assignments and records.',
        compass: {
            matchScore: 80,
            contextualNarrative: 'Gain "inside baseball" knowledge of the detailing process. Working directly at NPC gives you insight into how slates are built and careers are managed. Networking opportunities here are immense, though the location is less desirable than fleet concentration areas.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b10-uss-zumwalt',
        title: 'WEAPONS SYS TECH',
        uic: '89012',
        location: 'SAN DIEGO, CA',
        payGrade: 'E-6',
        nec: 'V02A',
        dutyType: 'SEA',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 240 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Advanced weapons system maintenance.',
        compass: {
            matchScore: 82,
            contextualNarrative: 'Work on the cutting edge of naval technology aboard the DDG-1000 class. This platform requires technicians who can adapt to new, often experimental systems. Your troubleshooting history suggests you would thrive in this dynamic engineering environment.',
        },
        advertisementStatus: 'projected',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b11-navwar',
        title: 'PROJECT MANAGER',
        uic: '90123',
        location: 'SAN DIEGO, CA',
        payGrade: 'E-7',
        nec: 'H12A',
        dutyType: 'SHORE',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 240 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Manage NAVWAR IT projects.',
        compass: {
            matchScore: 70,
            contextualNarrative: 'This is a stretch assignment typically slated for an E-7, but your package is competitive for a waiver. It involves high-level acquisition program management. Success here would be a definitive "sustained superior performance" indicator for your Chief package.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b12-uss-america',
        title: 'RADIO DIV SUPER',
        uic: '01234',
        location: 'SASEBO, JAPAN',
        payGrade: 'E-6',
        nec: 'H04A',
        dutyType: 'SEA',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 260 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Leading Radio division on LHA-6.',
        compass: {
            matchScore: 90,
            contextualNarrative: 'An urgent fill for a critical leadership gap. You would be stepping immediately into a Division Leading Petty Officer (DLPO) role on a forward-deployed big deck amphib. The responsibility is massive, but the rewards and visibility are equally significant.',
        },
        advertisementStatus: 'projected',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b13-pentagon',
        title: 'JOINT STAFF SUPPORT',
        uic: '10101',
        location: 'ARLINGTON, VA',
        payGrade: 'E-6',
        nec: 'H08A',
        dutyType: 'SHORE',
        targetRating: 'IT',
        reportNotLaterThan: new Date(Date.now() + 300 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'IT support for Joint Staff J6.',
        compass: {
            matchScore: 95,
            contextualNarrative: 'The ultimate prestige shore duty. You will be supporting flag officers and senior civilians in the Joint Staff environment. Requires impeccable bearing, top-tier technical skills, and a TS/SCI clearance. This is a "purple" assignment that looks fantastic on a resume.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },

    // =============================================================================
    // AT BILLETS (Persona A — AT1 Trent, Avionics Technician)
    // =============================================================================
    {
        id: 'b14-uss-nimitz-ciws',
        title: 'CIWS TECHNICIAN',
        uic: '09420',
        location: 'BREMERTON, WA',
        payGrade: 'E-6',
        nec: '8341',
        dutyType: 'SEA',
        targetRating: 'AT',
        reportNotLaterThan: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Lead CIWS Mk 15 maintenance and combat system readiness on USS Nimitz (CVN-68).',
        compass: {
            matchScore: 97,
            contextualNarrative: 'Your CIWS Block 1B NEC and prior CVN experience on Nimitz make this a near-perfect match. Returning to a platform you know well lets you hit the ground running as the senior CIWS tech. Strong discriminator for Chief.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b15-aimd-whidbey',
        title: 'AVIONICS BENCH LEAD',
        uic: '61023',
        location: 'OAK HARBOR, WA',
        payGrade: 'E-6',
        nec: '8301',
        dutyType: 'SHORE',
        targetRating: 'AT',
        reportNotLaterThan: new Date(Date.now() + 150 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Lead avionics intermediate-level repair at AIMD NAS Whidbey Island. IFF/SIF and radar bench expertise required.',
        compass: {
            matchScore: 91,
            contextualNarrative: 'A return to AIMD Whidbey where you served as an AT2. This time you would lead the bench. Your IFF NEC and CDQAR qualification make you the ideal candidate for quality assurance oversight on P-3/P-8 avionics components.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b16-cnattu-pensacola',
        title: 'AT A-SCHOOL INSTRUCTOR',
        uic: '62180',
        location: 'PENSACOLA, FL',
        payGrade: 'E-6',
        nec: '9502',
        dutyType: 'SHORE',
        targetRating: 'AT',
        reportNotLaterThan: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Instructor for Aviation Electronics Technician A-School at CNATTU Pensacola.',
        compass: {
            matchScore: 86,
            contextualNarrative: 'An instructor tour is a proven Chief-maker. Your breadth across CIWS, IFF, and QA makes you a well-rounded candidate to teach the next generation of ATs. NEC 9502 (Instructor) will be awarded upon completion of NITC.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b17-vfa-195',
        title: 'AVIONICS DIV LEAD',
        uic: '09880',
        location: 'IWAKUNI, JAPAN',
        payGrade: 'E-6',
        nec: '8342',
        dutyType: 'SEA',
        targetRating: 'AT',
        reportNotLaterThan: new Date(Date.now() + 200 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Lead Avionics Division for VFA-195 "Dambusters" flying F/A-18E. FDNF Japan.',
        compass: {
            matchScore: 93,
            contextualNarrative: 'Forward Deployed Naval Forces Japan with a storied strike fighter squadron. Your EAWS pin and CIWS Block 1B NEC translate directly to F/A-18E avionics leadership. High-visibility DLPO role with direct AIRLANT mentoring.',
        },
        advertisementStatus: 'projected',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b18-nawcad-pax',
        title: 'TEST AVIONICS TECH',
        uic: '63450',
        location: 'PATUXENT RIVER, MD',
        payGrade: 'E-6',
        nec: '8342',
        dutyType: 'SHORE',
        targetRating: 'AT',
        reportNotLaterThan: new Date(Date.now() + 220 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Support flight test avionics integration at NAWCAD. Next-gen systems exposure.',
        compass: {
            matchScore: 84,
            contextualNarrative: 'A rare acquisition-side tour that exposes you to next-generation avionics before fleet introduction. Excellent for broadening beyond pure maintenance into systems engineering. COOL credential opportunities in project management abound.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b19-uss-eisenhower-at',
        title: 'AVIATION ELECT LEAD',
        uic: '09510',
        location: 'NORFOLK, VA',
        payGrade: 'E-6',
        nec: '8341',
        dutyType: 'SEA',
        targetRating: 'AT',
        reportNotLaterThan: new Date(Date.now() + 110 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Lead AT shop aboard USS Eisenhower (CVN-69). Deployment imminent.',
        compass: {
            matchScore: 89,
            contextualNarrative: 'Urgent fill on a carrier about to deploy. You would step into an LPO role with a 45-person division. High risk, high reward — sailors who deploy in leadership roles on short notice are consistently recognized at selection boards.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },

    // =============================================================================
    // SWO BILLETS (Persona B — LT Navarro, Surface Warfare Officer)
    // =============================================================================
    {
        id: 'b20-uss-preble-dh',
        title: 'DEPT HEAD — OPS',
        uic: '21890',
        location: 'SAN DIEGO, CA',
        payGrade: 'O-3',
        designator: '1110',
        dutyType: 'SEA',
        targetRating: 'SWO',
        reportNotLaterThan: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Operations Department Head on USS Preble (DDG-88). SWO qualified, TAO certified required.',
        compass: {
            matchScore: 96,
            contextualNarrative: 'The premier milestone tour for a SWO lieutenant. Your OOD Underway and TAO-under-instruction quals from USS Halsey position you for immediate success. Completing DH on a Burke-class is the single most important career gate for O-4 selection.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b21-surflant-n3',
        title: 'READINESS OFFICER',
        uic: '32100',
        location: 'NORFOLK, VA',
        payGrade: 'O-3',
        designator: '1110',
        dutyType: 'SHORE',
        targetRating: 'SWO',
        reportNotLaterThan: new Date(Date.now() + 160 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'SURFLANT N3 Readiness Officer. Track fleet material and training readiness.',
        compass: {
            matchScore: 82,
            contextualNarrative: 'A Type Commander staff tour that gives you visibility into fleet-wide readiness metrics. While not a DH tour, this broadens your operational perspective and exposes you to the flag-level planning process. Strong networking for future command screening.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b22-uss-jackson-lcs',
        title: 'EXECUTIVE OFFICER',
        uic: '21950',
        location: 'SAN DIEGO, CA',
        payGrade: 'O-3',
        designator: '1110',
        dutyType: 'SEA',
        targetRating: 'SWO',
        reportNotLaterThan: new Date(Date.now() + 100 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'XO aboard USS Jackson (LCS-6). Small-crew leadership. Deploy-ready.',
        compass: {
            matchScore: 90,
            contextualNarrative: 'An accelerated path to command. LCS XO billets are open to junior O-3s and provide the full scope of command responsibility with a crew of 70. Your DCA experience and engineering background from Halsey make you a strong fit for this multi-mission platform.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b23-nrotc-sdsu',
        title: 'NROTC INSTRUCTOR',
        uic: '40210',
        location: 'SAN DIEGO, CA',
        payGrade: 'O-3',
        designator: '1110',
        dutyType: 'SHORE',
        targetRating: 'SWO',
        reportNotLaterThan: new Date(Date.now() + 250 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Naval Science Instructor at San Diego State NROTC unit.',
        compass: {
            matchScore: 74,
            contextualNarrative: 'A unique shore tour that keeps you in San Diego while mentoring future officers. Instructor duty is well-regarded on O-4 boards and offers a predictable schedule. However, it delays your DH tour, which should be factored into your career timeline.',
        },
        advertisementStatus: 'projected',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b24-uss-chosin-dh',
        title: 'DEPT HEAD — WEPS',
        uic: '21760',
        location: 'PEARL HARBOR, HI',
        payGrade: 'O-3',
        designator: '1110',
        dutyType: 'SEA',
        targetRating: 'SWO',
        reportNotLaterThan: new Date(Date.now() + 140 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Weapons Department Head on USS Chosin (CG-65). AEGIS cruiser, deploy imminent.',
        compass: {
            matchScore: 88,
            contextualNarrative: 'A Ticonderoga-class cruiser DH tour in Pearl Harbor. WEPS on a CG carries enormous responsibility managing the BMD and AEGIS combat system. This tour is an accelerant for early command and O-5 screening, though the tempo will be relentless.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },

    // =============================================================================
    // ETN BILLETS (Persona C — ETN1 Hargrove, Submarine Nuclear Electrician)
    // =============================================================================
    {
        id: 'b25-uss-virginia-ssn',
        title: 'REACTOR DEPT LPO',
        uic: '21300',
        location: 'GROTON, CT',
        payGrade: 'E-6',
        nec: '3364',
        dutyType: 'SEA',
        targetRating: 'ETN',
        reportNotLaterThan: new Date(Date.now() + 100 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Reactor Department LPO aboard USS Virginia (SSN-774). Nuclear shift supervisor qualified required.',
        compass: {
            matchScore: 95,
            contextualNarrative: 'Your shift supervisor NEC and prior SSN experience on Hartford make this an ideal fit. As reactor LPO on a Virginia-class, you will lead the electrical division through a deployment cycle. This is the definitive Chief-making tour for a nuke ET.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b26-nptu-charleston',
        title: 'PROTOTYPE INSTRUCTOR',
        uic: '63800',
        location: 'GOOSE CREEK, SC',
        payGrade: 'E-6',
        nec: '3359',
        dutyType: 'SHORE',
        targetRating: 'ETN',
        reportNotLaterThan: new Date(Date.now() + 130 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Staff instructor at Nuclear Power Training Unit Charleston. Teach reactor plant operations on MTS-635.',
        compass: {
            matchScore: 92,
            contextualNarrative: 'A return to NPTU Charleston where you earned your shift supervisor qualification. This time as an instructor, you will shape the next class of nuclear operators. Instructor duty is consistently one of the highest-weighted factors on nuke Chief selection boards.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b27-uss-columbia-ssbn',
        title: 'ELECTRICAL DIV LCPO',
        uic: '21450',
        location: 'KINGS BAY, GA',
        payGrade: 'E-6',
        nec: '3353',
        dutyType: 'SEA',
        targetRating: 'ETN',
        reportNotLaterThan: new Date(Date.now() + 170 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Electrical Division LCPO on USS Columbia (SSBN-826). First Columbia-class boat, pre-commissioning crew.',
        compass: {
            matchScore: 87,
            contextualNarrative: 'A once-in-a-generation opportunity to be part of the first Columbia-class SSBN crew. Pre-com duty is grueling but the prestige and "plank owner" status is unmatched. Your SSBN experience on Louisiana transfers directly to this next-gen platform.',
        },
        advertisementStatus: 'projected',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b28-navsea-08',
        title: 'TECH ADVISOR (NAVSEA 08)',
        uic: '64100',
        location: 'WASHINGTON, DC',
        payGrade: 'E-7',
        nec: '3364',
        dutyType: 'SHORE',
        targetRating: 'ETN',
        reportNotLaterThan: new Date(Date.now() + 200 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Technical advisor to Naval Reactors (NAVSEA 08). Support reactor safety and fleet readiness policy.',
        compass: {
            matchScore: 78,
            contextualNarrative: 'A stretch billet at E-7 but waiver-eligible given your EWS and shift supervisor qualifications. Working at Naval Reactors HQ provides unparalleled insight into reactor policy. Few billets carry more prestige in the nuke community, though DC living costs are significant.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b29-uss-jimmy-carter',
        title: 'REACTOR OPERATOR',
        uic: '21380',
        location: 'BANGOR, WA',
        payGrade: 'E-6',
        nec: '3353',
        dutyType: 'SEA',
        targetRating: 'ETN',
        reportNotLaterThan: new Date(Date.now() + 80 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Reactor operator aboard USS Jimmy Carter (SSN-23). Seawolf-class, special missions capable.',
        compass: {
            matchScore: 90,
            contextualNarrative: 'One of only three Seawolf-class submarines, Jimmy Carter is a unique platform with expanded mission capabilities. Your prior SSN and SSBN reactor experience gives you the versatility this crew demands. Bangor keeps you in the Pacific Northwest near family.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
    {
        id: 'b30-nnptc-instructor',
        title: 'NUKE POWER SCHOOL INSTR',
        uic: '63900',
        location: 'GOOSE CREEK, SC',
        payGrade: 'E-6',
        nec: '3359',
        dutyType: 'SHORE',
        targetRating: 'ETN',
        reportNotLaterThan: new Date(Date.now() + 160 * 24 * 60 * 60 * 1000).toISOString(),
        billetDescription: 'Classroom instructor at Nuclear Power School (NNPTC). Teach electrical theory and reactor plant systems.',
        compass: {
            matchScore: 85,
            contextualNarrative: 'Nuclear Power School instructor duty is the gold standard shore tour for nuke Chiefs. Your ELT qualification adds depth to your teaching capability. Charleston offers affordable living and strong school districts for your family.',
        },
        advertisementStatus: 'confirmed_open',
        lastSyncTimestamp: new Date().toISOString(),
        syncStatus: 'synced',
    },
];
