/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./app/(hub)/**/*.{js,jsx,ts,tsx}",
    "./app/(pcs)/**/*.{js,jsx,ts,tsx}",
    "./app/(assignment)/**/*.{js,jsx,ts,tsx}",
    "./app/(admin)/**/*.{js,jsx,ts,tsx}",
    "./app/(profile)/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)",
        "surface-tint": "rgb(var(--color-surface-tint) / <alpha-value>)",
        "primary": "rgb(var(--color-primary) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--color-on-primary-fixed) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "on-tertiary": "rgb(var(--color-on-tertiary) / <alpha-value>)",
        "surface-variant": "rgb(var(--color-surface-variant) / <alpha-value>)",
        "secondary-container": "rgb(var(--color-secondary-container) / <alpha-value>)",
        "on-secondary": "rgb(var(--color-on-secondary) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)",
        "on-error-container": "rgb(var(--color-on-error-container) / <alpha-value>)",
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "primary-fixed": "rgb(var(--color-primary-fixed) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
        "error": "rgb(var(--color-error) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--color-on-secondary-container) / <alpha-value>)",
        "tertiary-container": "rgb(var(--color-tertiary-container) / <alpha-value>)",
        "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
        "error-container": "rgb(var(--color-error-container) / <alpha-value>)",
        "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
        "on-background": "rgb(var(--color-on-background) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--color-on-tertiary-container) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        "surface-dim": "rgb(var(--color-surface-dim) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--color-secondary-fixed) / <alpha-value>)",
        "on-error": "rgb(var(--color-on-error) / <alpha-value>)",
        "inverse-primary": "rgb(var(--color-inverse-primary) / <alpha-value>)",
        "background": "rgb(var(--color-background) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--color-inverse-on-surface) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--color-tertiary-fixed) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "outline": "rgb(var(--color-outline) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--color-on-secondary-fixed) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)",
        "inverse-surface": "rgb(var(--color-inverse-surface) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--color-secondary-fixed-dim) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--color-primary-fixed-dim) / <alpha-value>)",
        "surface-bright": "rgb(var(--color-surface-bright) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--color-on-tertiary-fixed) / <alpha-value>)",
        "on-primary-container": "rgb(var(--color-on-primary-container) / <alpha-value>)",
        "tertiary": "rgb(var(--color-tertiary) / <alpha-value>)",

        // Legacy fallbacks updated to enforce 100% opacity instead of `<alpha-value>` to strictly prevent glassmorphism classes
        systemGray: "rgb(var(--color-system-gray) / 1)",
        systemGray6: "rgb(var(--color-system-gray6) / 1)",
        systemBlue: "rgb(var(--color-system-blue) / 1)",
        navyBlue: "rgb(var(--color-navy-blue) / 1)",
        navyLight: "#1E3A5F",
        navyGold: "rgb(var(--color-navy-gold) / 1)",
        systemBackground: "rgb(var(--color-background) / 1)",
        labelPrimary: "rgb(var(--color-label-primary) / 1)",
        labelSecondary: "rgb(var(--color-label-secondary) / 1)",
        cardBackground: "rgb(var(--color-card-background) / 1)",
        wizardCardBackground: "rgb(var(--color-wizard-card-background) / 1)",
        inputBackground: "rgb(var(--color-input-background) / 1)",
        accentText: "rgb(var(--color-accent-text) / 1)",
      },
      fontFamily: {
        sans: ['Lexend', 'Lexend_400Regular', 'System'],
        medium: ['Lexend', 'Lexend_500Medium', 'System'],
        semibold: ['Lexend', 'Lexend_600SemiBold', 'System'],
        bold: ['Lexend', 'Lexend_700Bold', 'System'],
        extrabold: ['Lexend', 'Lexend_800ExtraBold', 'System'],
        black: ['Lexend', 'Lexend_900Black', 'System'],
        headline: ['Lexend', 'Lexend_700Bold', 'System'],
        display: ['Lexend', 'Lexend_800ExtraBold', 'System'],
        body: ['Lexend', 'Lexend_400Regular', 'System'],
        label: ['Lexend', 'Lexend_500Medium', 'System'],
      },
      boxShadow: {
        "apple-sm": "0 2px 0 0 rgba(10, 22, 40, 1)",
        "apple-md": "0 4px 0 0 rgba(10, 22, 40, 1)",
        "apple-lg": "0 6px 0 0 rgba(10, 22, 40, 1)",
      },
      borderRadius: {
        // Enforce the 0px roundedness rule across tailwind utility classes except 'full'
        'none': '0px',
        'sm': '0px',
        DEFAULT: '0px',
        'md': '0px',
        'lg': '0px',
        'xl': '0px',
        '2xl': '0px',
        '3xl': '0px',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}
