/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./app/(hub)/**/*.{js,jsx,ts,tsx}",
    "./app/(pcs)/**/*.{js,jsx,ts,tsx}",
    "./app/(assignment)/**/*.{js,jsx,ts,tsx}",
    "./app/(admin)/**/*.{js,jsx,ts,tsx}",
    "./app/(profile)/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#2e4675",
        "surface-tint": "#aec6fe",
        "primary": "rgb(var(--color-primary) / <alpha-value>)",
        "on-primary-fixed": "#001a42",
        "surface-container-high": "#2a2a2a",
        "on-tertiary": "#2f3131",
        "surface-variant": "#353534",
        "secondary-container": "#fdc400",
        "on-secondary": "#3e2e00",
        "on-tertiary-fixed-variant": "#454747",
        "on-error-container": "#ffdad6",
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "on-surface-variant": "#c4c6d0",
        "on-surface": "#e5e2e1",
        "primary-fixed": "#d8e2ff",
        "outline-variant": "#44474f",
        "secondary": "rgb(var(--color-secondary-container) / <alpha-value>)",
        "error": "#ffb4ab",
        "on-secondary-container": "#6c5200",
        "tertiary-container": "#202222",
        "surface-container": "#201f1f",
        "error-container": "#93000a",
        "surface-container-low": "#1c1b1b",
        "primary-container": "#00204e",
        "on-background": "#e5e2e1",
        "on-tertiary-container": "#888989",
        "surface-container-highest": "#353534",
        "on-primary": "#142f5d",
        "surface-dim": "#131313",
        "secondary-fixed": "#ffdf96",
        "on-error": "#690005",
        "inverse-primary": "#465e8f",
        "background": "rgb(var(--color-background) / <alpha-value>)",
        "inverse-on-surface": "#313030",
        "tertiary-fixed-dim": "#c6c6c7",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "outline": "#8e909a",
        "on-secondary-fixed": "#251a00",
        "on-secondary-fixed-variant": "#594400",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed-dim": "#f6bf00",
        "primary-fixed-dim": "#aec6fe",
        "surface-bright": "#393939",
        "on-tertiary-fixed": "#1a1c1c",
        "on-primary-container": "#7189bc",
        "tertiary": "#c6c6c7",

        // Legacy fallbacks updated to enforce 100% opacity instead of `<alpha-value>` to strictly prevent glassmorphism classes
        systemGray: "rgb(var(--color-system-gray) / 1)",
        systemGray6: "rgb(var(--color-system-gray6) / 1)",
        systemBlue: "rgb(var(--color-system-blue) / 1)",
        navyBlue: "rgb(var(--color-navy-blue) / 1)",
        navyLight: "#1E3A5F",
        navyGold: "rgb(var(--color-navy-gold) / 1)",
        systemBackground: "rgb(var(--color-background) / 1)",
        labelPrimary: "rgb(var(--color-label-primary) / 1)",
        labelSecondary: "rgb(var(--color-label-secondary) / 1)",
        cardBackground: "rgb(var(--color-card-background) / 1)",
        wizardCardBackground: "rgb(var(--color-wizard-card-background) / 1)",
        inputBackground: "rgb(var(--color-input-background) / 1)",
        accentText: "rgb(var(--color-accent-text) / 1)",
      },
      fontFamily: {
        sans: ['Lexend_400Regular', 'System'],
        medium: ['Lexend_500Medium', 'System'],
        semibold: ['Lexend_600SemiBold', 'System'],
        bold: ['Lexend_700Bold', 'System'],
        extrabold: ['Lexend_800ExtraBold', 'System'],
        black: ['Lexend_900Black', 'System'],
        headline: ['Lexend_700Bold', 'System'],
        display: ['Lexend_800ExtraBold', 'System'],
        body: ['Lexend_400Regular', 'System'],
        label: ['Lexend_500Medium', 'System'],
      },
      boxShadow: {
        "apple-sm": "0 2px 0 0 rgba(10, 22, 40, 1)",
        "apple-md": "0 4px 0 0 rgba(10, 22, 40, 1)",
        "apple-lg": "0 6px 0 0 rgba(10, 22, 40, 1)",
      },
      borderRadius: {
        // Enforce the 0px roundedness rule across tailwind utility classes except 'full'
        'none': '0px',
        'sm': '0px',
        DEFAULT: '0px',
        'md': '0px',
        'lg': '0px',
        'xl': '0px',
        '2xl': '0px',
        '3xl': '0px',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}
